import Header from "@/components/header/Header";
import Head from "next/head";

export default function Page() {
  return <>
    <Head>
      <title>MKS Front End Challenge</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" imageSrcSet="@/../public/favicon.ico" />
    </Head>
    <main>
      <Header />
    </main>
  </>
}
